### ISSUE TITLE
Can I use a Quilibrium service with a different name?

### ISSUE THREAD

**Issue by lamat1111** [fpatron/Quilibrium-Dashboard#2]
What great tool you have created :)
I'd like to keep my Quilibrium service name though (ceremonyclient) because it is supported by the many guides out there for all the custom commands.
Where in your code can I make an edit to keep my service name? I took a quick look but could not find it.
Thanks!

**Comment by mjessup** [comment]
I made some modifications for this program to work, I haven't fully set it up just yet but I'll share what I did so far:

Here is the modified version of the quilibrium_exporter.py (note: author made commits sense I modified this)
```python
from flask import Flask, Response
from prometheus_client import start_http_server, Gauge, CollectorRegistry, generate_latest
import subprocess
import socket
import re
import os

app = Flask(__name__)

# Define the working directory
#current_dir = os.path.dirname(os.path.abspath(__file__))
#working_directory = f'{current_dir}/../ceremonyclient/node'

# Define the registry
registry = CollectorRegistry()

# Define custom metrics
peer_score_metric = Gauge('quilibrium_peer_score', 'Peer score of the node', ['peer_id', 'hostname'], registry=registry)
max_frame_metric = Gauge('quilibrium_max_frame', 'Max frame of the node', ['peer_id', 'hostname'], registry=registry)
unclaimed_balance_metric = Gauge('quilibrium_unclaimed_balance', 'Unclaimed balance of the node', ['peer_id', 'hostname'], registry=registry)
peer_store_count_metric = Gauge('quilibrium_peer_store_count', 'Peers in store', ['peer_id', 'hostname'], registry=registry)
network_peer_count_metric = Gauge('quilibrium_network_peer_count', 'Network peer count', ['peer_id', 'hostname'], registry=registry)
proof_increment_metric = Gauge('quilibrium_proof_increment', 'Proof increment', ['peer_id', 'hostname'], registry=registry)
proof_time_taken_metric = Gauge('quilibrium_proof_time_taken', 'Proof time taken', ['peer_id', 'hostname'], registry=registry)

# Function to fetch data from command
def fetch_data_from_node():
    try:
        # Define the command to get the node version and run the node binary
        command = """
        version_file="/root/ceremonyclient/node/config/version.go"; 
        version_hex=$(grep -A 1 "func GetVersion() \[\]byte {" "$version_file" | grep -Eo '0x[0-9a-fA-F]+' | xargs printf "%d.%d.%d"); 
        arch=$(uname -m); 
        node_binary=$(case $arch in x86_64) echo "node-$version_hex-linux-amd64" ;; aarch64) echo "node-$version_hex-linux-arm64" ;; arm64) echo "node-$version_hex-darwin-arm64" ;; *) echo "Unsupported architecture: $arch"; exit 1 ;; esac); 
        cd /root/ceremonyclient/node/ && ./$node_binary --node-info
        """
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        output = result.stdout
        
        peer_id_match = re.search(r'Peer ID: (\S+)', output)
        peer_id = peer_id_match.group(1) if peer_id_match else 'unknown'
        
        peer_score_match = re.search(r'Peer Score: (\d+)', output)
        peer_score = float(peer_score_match.group(1)) if peer_score_match else 0
        
        max_frame_match = re.search(r'Max Frame: (\d+)', output)
        max_frame = float(max_frame_match.group(1)) if max_frame_match else 0
        
        unclaimed_balance_match = re.search(r'Unclaimed balance: ([\d\.]+)', output)
        unclaimed_balance = float(unclaimed_balance_match.group(1)) if unclaimed_balance_match else 0
        
        hostname = socket.gethostname()
        
        peer_score_metric.labels(peer_id=peer_id, hostname=hostname).set(peer_score)
        max_frame_metric.labels(peer_id=peer_id, hostname=hostname).set(max_frame)
        unclaimed_balance_metric.labels(peer_id=peer_id, hostname=hostname).set(unclaimed_balance)

        return peer_id, hostname

    except Exception as e:
        print(f"Error fetching data from command: {e}")
        return None, None


# Function to fetch data from logs
def fetch_data_from_logs(peer_id, hostname):
    try:
        # Use journalctl to get logs from the last hour for the specified service
        result = subprocess.run(['journalctl', '-u', 'ceremonyclient', '--since', '-1h', '--no-pager'], capture_output=True, text=True)
        output = result.stdout.splitlines()

        peer_store_count = None
        network_peer_count = None
        proof_increment = None
        proof_time_taken = None

        for line in reversed(output):
            if peer_store_count is None and 'peers in store' in line:
                peer_store_count_match = re.search(r'"peer_store_count":(\d+)', line)
                network_peer_count_match = re.search(r'"network_peer_count":(\d+)', line)
                if peer_store_count_match and network_peer_count_match:
                    peer_store_count = int(peer_store_count_match.group(1))
                    network_peer_count = int(network_peer_count_match.group(1))
                    peer_store_count_metric.labels(peer_id=peer_id, hostname=hostname).set(peer_store_count)
                    network_peer_count_metric.labels(peer_id=peer_id, hostname=hostname).set(network_peer_count)
            if proof_increment is None and 'completed duration proof' in line:
                proof_increment_match = re.search(r'"increment":(\d+)', line)
                proof_time_taken_match = re.search(r'"time_taken":([\d\.]+)', line)
                if proof_increment_match and proof_time_taken_match:
                    proof_increment = int(proof_increment_match.group(1))
                    proof_time_taken = float(proof_time_taken_match.group(1))
                    proof_increment_metric.labels(peer_id=peer_id, hostname=hostname).set(proof_increment)
                    proof_time_taken_metric.labels(peer_id=peer_id, hostname=hostname).set(proof_time_taken)
            
            if (peer_store_count is not None and network_peer_count is not None and 
                proof_increment is not None and proof_time_taken is not None):
                break

    except Exception as e:
        print(f"Error fetching data from logs: {e}")

@app.route('/metrics')
def metrics():
    peer_id, hostname = fetch_data_from_node()
    if peer_id and hostname:
        fetch_data_from_logs(peer_id, hostname)
    return Response(generate_latest(registry), mimetype='text/plain')

if __name__ == '__main__':
    start_http_server(8000)
    app.run(host='127.0.0.1', port=5001)
``` 

Still a work in progress; I'll share more detailed info once I get it up and running.
It would be great @lamat1111  if you could integrate this tool to be easily set up through your quick start scripts :)

**Comment by vodhash** [comment]
> What great tool you have created :) I'd like to keep my Quilibrium service name though (ceremonyclient) because it is supported by the many guides out there for all the custom commands. Where in your code can I make an edit to keep my service name? I took a quick look but could not find it. Thanks!

Hi @lamat1111 ,
Thanks for your comment.

You can change the service name at this line.
https://github.com/fpatron/Quilibrium-Dashboard/blob/0762b372b9c4fbd0ff3af341164dc42043c5d1f8/grafana/exporter/quilibrium_exporter.py#L59

This grafana dashboard is linked to another project I made to simplify deployment of nodes in your infrastructure (see my project quilibrium toolkit). It uses ansible projet.

Note that I made a symbolic link to rename the main binary to launch the node. That why I call the file node to get node info. The rest api doesn't give me enough data.
I didn't push yet the last version which find automatically the node process.

**Comment by mjessup** [comment]
> > What great tool you have created :) I'd like to keep my Quilibrium service name though (ceremonyclient) because it is supported by the many guides out there for all the custom commands. Where in your code can I make an edit to keep my service name? I took a quick look but could not find it. Thanks!
> 
> Hi @lamat1111 , Thanks for your comment.
> 
> You can change the service name at this line.
> 
> https://github.com/fpatron/Quilibrium-Dashboard/blob/0762b372b9c4fbd0ff3af341164dc42043c5d1f8/grafana/exporter/quilibrium_exporter.py#L59
> 
> This grafana dashboard is linked to another project I made to simplify deployment of nodes in your infrastructure (see my project quilibrium toolkit). It uses ansible projet.
> 
> Note that I made a symbolic link to rename the main binary to launch the node. That why I call the file node to get node info. The rest api doesn't give me enough data. I didn't push yet the last version which find automatically the node process.

Any ETA for the latest version to be published? Also do I need to make a victoriametrics config file with my node ip's in it?

Thanks again, you have the best dashboard/monitoring program for these nodes :)

**Comment by lamat1111** [comment]
> > What great tool you have created :) I'd like to keep my Quilibrium service name though (ceremonyclient) because it is supported by the many guides out there for all the custom commands. Where in your code can I make an edit to keep my service name? I took a quick look but could not find it. Thanks!
> 
> Hi @lamat1111 , Thanks for your comment.
> 
> You can change the service name at this line.
> 
> https://github.com/fpatron/Quilibrium-Dashboard/blob/0762b372b9c4fbd0ff3af341164dc42043c5d1f8/grafana/exporter/quilibrium_exporter.py#L59
> 
> This grafana dashboard is linked to another project I made to simplify deployment of nodes in your infrastructure (see my project quilibrium toolkit). It uses ansible projet.
> 
> Note that I made a symbolic link to rename the main binary to launch the node. That why I call the file node to get node info. The rest api doesn't give me enough data. I didn't push yet the last version which find automatically the node process.

Thank you!

**Comment by vodhash** [comment]
Hi @lamat1111 @mjessup 

I pushed a new version of the node exporter.
You can now override the service name and node path by creating a .env file with these parameters :
```
service_name=
node_path=
```
Enjoy and don't hesitate if needed

**Comment by mjessup** [comment]
> Hi @lamat1111 @mjessup
> 
> I pushed a new version of the node exporter. You can now override the service name and node path by creating a .env file with these parameters :
> 
> ```
> service_name=
> node_path=
> ```
> 
> Enjoy and don't hesitate if needed

Thanks, 1 quick question before I try and set this up again.
Is there anything missing in the readme that I may need to set this up? I got a VPS to install the dashboard on as I have more than 5 node's I'd want to monitor. Is there a .yml file I need to make for Victoria Metrics with my node ip's in it? I havent set up any Grafana dashboards before, so this is a bit of a learning curve for me.

thanks again.

**Comment by vodhash** [comment]
Hi @mjessup 
To facilitate the installation of Grafana, Loki, and Victoria Metrics on your VPS, you can use the provided Docker file. Everything will be directly configured for the Grafana server.
You will just need to configure Grafana Alloy on your 5 nodes. The project's README is usually comprehensive.
