### ISSUE TITLE
Grafana Dash showing nil ammounts and no peer ids

### ISSUE THREAD

**Issue by examare** [fpatron/Quilibrium-Dashboard#3]
Firstly, congratulation on developing a great toolI
Having issues with approx 20% of my nodes showing nil Quilibrium ammounts and no peer ids but Server resources overview is showing their usage and stats.
All nodes are identical (deb12) and used .env (as not using default path and service name), 80% of nodes working great but been scratching head with inconsistency tried reinstalling but that hasn't helped.
Any ideas would be much appreciated.

**Comment by vodhash** [comment]
Hi @examare 
Could you give me your node logs for alloy service et quilibrium_exporter?
```
journalctl -u alloy -f
journalctl -u quilibrium_exporter -f
```
And on one of your node which doesn't work, could you give me the output of :
```
curl http://127.0.0.1:5001/metrics
```

**Comment by examare** [comment]
Thanks for quick response, I think you identyfied culprit, the 'curl http://127.0.0.1:5001/metrics' is hanging, but works fine on fully functioning node, journal logs look ok, as follows: 
`root@R7-3700-1:~/grafana# journalctl -u alloy -f
Jul 04 19:44:21 R7-3700-1 alloy[1305]: ts=2024-07-04T09:44:21.998212153Z level=info msg="series GC completed" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal duration=547.675µs
Jul 04 21:44:21 R7-3700-1 alloy[1305]: ts=2024-07-04T11:44:21.998960862Z level=info msg="series GC completed" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal duration=601.887µs
Jul 04 21:44:21 R7-3700-1 alloy[1305]: ts=2024-07-04T11:44:21.999070038Z level=info msg="Creating checkpoint" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal from_segment=12 to_segment=13 mint=1720093153000
Jul 04 21:44:22 R7-3700-1 alloy[1305]: ts=2024-07-04T11:44:22.235337842Z level=info msg="WAL checkpoint complete" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal first=12 last=13 duration=236.978015ms
Jul 04 22:31:21 R7-3700-1 alloy[1305]: ts=2024-07-04T12:31:21.415565082Z level=info msg="reporting Alloy stats" date=2024-07-04T22:31:21.415+10:00
Jul 04 22:31:21 R7-3700-1 alloy[1305]: ts=2024-07-04T12:31:21.65147165Z level=info msg="usage report sent with success"
Jul 04 23:44:22 R7-3700-1 alloy[1305]: ts=2024-07-04T13:44:22.236790089Z level=info msg="series GC completed" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal duration=669.835µs
Jul 05 01:44:22 R7-3700-1 alloy[1305]: ts=2024-07-04T15:44:22.238283876Z level=info msg="series GC completed" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal duration=700.032µs
Jul 05 01:44:22 R7-3700-1 alloy[1305]: ts=2024-07-04T15:44:22.238474396Z level=info msg="Creating checkpoint" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal from_segment=14 to_segment=15 mint=1720107553000
Jul 05 01:44:22 R7-3700-1 alloy[1305]: ts=2024-07-04T15:44:22.248263697Z level=info msg="WAL checkpoint complete" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal first=14 last=15 duration=10.679733ms`

`root@R7-3700-1:~/grafana# journalctl -u quilibrium_exporter -f
Jul 05 01:54:35 R7-3700-1 python[6393]: 2024-07-05 01:54:35,524 - INFO - 127.0.0.1 - - [05/Jul/2024 01:54:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 01:55:35 R7-3700-1 python[6393]: 2024-07-05 01:55:35,528 - INFO - 127.0.0.1 - - [05/Jul/2024 01:55:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 01:56:35 R7-3700-1 python[6393]: 2024-07-05 01:56:35,533 - INFO - 127.0.0.1 - - [05/Jul/2024 01:56:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 01:57:35 R7-3700-1 python[6393]: 2024-07-05 01:57:35,521 - INFO - 127.0.0.1 - - [05/Jul/2024 01:57:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 01:58:35 R7-3700-1 python[6393]: 2024-07-05 01:58:35,526 - INFO - 127.0.0.1 - - [05/Jul/2024 01:58:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 01:59:35 R7-3700-1 python[6393]: 2024-07-05 01:59:35,528 - INFO - 127.0.0.1 - - [05/Jul/2024 01:59:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 02:00:35 R7-3700-1 python[6393]: 2024-07-05 02:00:35,524 - INFO - 127.0.0.1 - - [05/Jul/2024 02:00:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 02:01:35 R7-3700-1 python[6393]: 2024-07-05 02:01:35,528 - INFO - 127.0.0.1 - - [05/Jul/2024 02:01:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 02:02:35 R7-3700-1 python[6393]: 2024-07-05 02:02:35,512 - INFO - 127.0.0.1 - - [05/Jul/2024 02:02:35] "GET /metrics HTTP/1.1" 200 -
Jul 05 02:03:35 R7-3700-1 python[6393]: 2024-07-05 02:03:35,518 - INFO - 127.0.0.1 - - [05/Jul/2024 02:03:35] "GET /metrics HTTP/1.1" 200 -`

**Comment by examare** [comment]
I also tested on another "faulty" node and got:
`root@q4os-m20:~/quil# journalctl -u alloy -f
Jul 04 11:26:34 q4os-m20 alloy[1523]: ts=2024-07-04T11:26:34.370877794Z level=info msg="now listening for http traffic" service=http addr=127.0.0.1:12345
Jul 04 11:26:34 q4os-m20 alloy[1523]: ts=2024-07-04T11:26:34.370089307Z level=info msg="starting cluster node" peers="" advertise_addr=127.0.0.1:12345
Jul 04 11:26:34 q4os-m20 alloy[1523]: ts=2024-07-04T11:26:34.371875678Z level=info msg="peers changed" new_peers=q4os-m20
Jul 04 11:27:06 q4os-m20 alloy[1523]: ts=2024-07-04T11:27:06.819446944Z level=info msg="Done replaying WAL" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=rw remote_name=7f01cd url=http://192.168.1.128:9090/api/v1/write duration=32.705272664s
Jul 04 12:43:33 q4os-m20 alloy[1523]: ts=2024-07-04T12:43:33.983097176Z level=info msg="reporting Alloy stats" date=2024-07-04T12:43:33.983Z
Jul 04 12:43:34 q4os-m20 alloy[1523]: ts=2024-07-04T12:43:34.188247248Z level=info msg="usage report sent with success"
Jul 04 13:26:34 q4os-m20 alloy[1523]: ts=2024-07-04T13:26:34.372592428Z level=info msg="series GC completed" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal duration=1.628957ms
Jul 04 13:26:34 q4os-m20 alloy[1523]: ts=2024-07-04T13:26:34.372882662Z level=info msg="Creating checkpoint" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal from_segment=6 to_segment=8 mint=1720099266000
Jul 04 13:26:34 q4os-m20 alloy[1523]: ts=2024-07-04T13:26:34.43407299Z level=info msg="WAL checkpoint complete" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal first=6 last=8 duration=63.109158ms
Jul 04 15:26:34 q4os-m20 alloy[1523]: ts=2024-07-04T15:26:34.436292495Z level=info msg="series GC completed" component_path=/ component_id=prometheus.remote_write.grafanacloud subcomponent=wal duration=1.414419ms`

`root@q4os-m20:~/quil# journalctl -u quilibrium_exporter -f
Jul 04 16:06:36 q4os-m20 python[828]: 2024-07-04 16:06:36,958 - INFO - 127.0.0.1 - - [04/Jul/2024 16:06:36] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:07:36 q4os-m20 python[828]: 2024-07-04 16:07:36,958 - INFO - 127.0.0.1 - - [04/Jul/2024 16:07:36] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:08:36 q4os-m20 python[828]: 2024-07-04 16:08:36,954 - INFO - 127.0.0.1 - - [04/Jul/2024 16:08:36] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:09:36 q4os-m20 python[828]: 2024-07-04 16:09:36,962 - INFO - 127.0.0.1 - - [04/Jul/2024 16:09:36] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:10:36 q4os-m20 python[828]: 2024-07-04 16:10:36,958 - INFO - 127.0.0.1 - - [04/Jul/2024 16:10:36] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:10:44 q4os-m20 python[828]: 2024-07-04 16:10:44,571 - INFO - 127.0.0.1 - - [04/Jul/2024 16:10:44] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:11:36 q4os-m20 python[828]: 2024-07-04 16:11:36,951 - INFO - 127.0.0.1 - - [04/Jul/2024 16:11:36] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:12:36 q4os-m20 python[828]: 2024-07-04 16:12:36,926 - INFO - 127.0.0.1 - - [04/Jul/2024 16:12:36] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:13:36 q4os-m20 python[828]: 2024-07-04 16:13:36,972 - INFO - 127.0.0.1 - - [04/Jul/2024 16:13:36] "GET /metrics HTTP/1.1" 200 -
Jul 04 16:14:36 q4os-m20 python[828]: 2024-07-04 16:14:36,969 - INFO - 127.0.0.1 - - [04/Jul/2024 16:14:36] "GET /metrics HTTP/1.1" 200 -`

`root@q4os-m20:~/quil# curl http://127.0.0.1:5001/metrics
# HELP quilibrium_peer_score Peer score of the node
# TYPE quilibrium_peer_score gauge
quilibrium_peer_score{hostname="q4os-m20",peer_id="unknown"} 0.0
# HELP quilibrium_max_frame Max frame of the node
# TYPE quilibrium_max_frame gauge
quilibrium_max_frame{hostname="q4os-m20",peer_id="unknown"} 0.0
# HELP quilibrium_unclaimed_balance Unclaimed balance of the node
# TYPE quilibrium_unclaimed_balance gauge
quilibrium_unclaimed_balance{hostname="q4os-m20",peer_id="unknown"} 0.0
# HELP quilibrium_peer_store_count Peers in store
# TYPE quilibrium_peer_store_count gauge
quilibrium_peer_store_count{hostname="q4os-m20",peer_id="unknown"} 74.0
# HELP quilibrium_network_peer_count Network peer count
# TYPE quilibrium_network_peer_count gauge
quilibrium_network_peer_count{hostname="q4os-m20",peer_id="unknown"} 12.0
# HELP quilibrium_proof_increment Proof increment
# TYPE quilibrium_proof_increment gauge
quilibrium_proof_increment{hostname="q4os-m20",peer_id="unknown"} 16707.0
# HELP quilibrium_proof_time_taken Proof time taken
# TYPE quilibrium_proof_time_taken gauge
quilibrium_proof_time_taken{hostname="q4os-m20",peer_id="unknown"} 71.318052992`

**Comment by examare** [comment]
Made some progress, modifying quilibrium_exporter.py and hard coding; node_binary & peer_id  seems to be partially working, and curl http://127.0.0.1:5001/metrics is getting all relevant data, grafana is mostly woorking but still missing "Peer id" & "Balance" for troublesome nodes in the "Qilibrium" panel.

**Comment by vodhash** [comment]
Hi @examare 
You can override the default path of the node using a .env file.
Create one and indicate the path of your node path:
```
node_path=
service_name=
```

**Comment by examare** [comment]
Yes, I already use .env (as not using default path and service name) but doesn't matter, I have to start from scratch as latest node update deleted all my /exporter directories :-(
